### PR TITLE
features/updaters-json

### PR DESCRIPTION
**Pull request by joshcampbell191**
Added support for `updaters.json`.

The API response will now contain a serialized representation of `updaters`.

```json
{
    "identifier": "jotego.jtmidres",
    "repository": {
        "platform": "github",
        "owner": "jotego",
        "name": "jtbin"
    },
    "download_url": "https://raw.githubusercontent.com/jotego/jtbin/master/pocket/zips/jotego.jtmidres.zip",
    "platform_id": "jtmidres",
    "version": "d2f3856",
    "release_date": "2024-10-04",
    "platform": {
        "category": "Arcade",
        "name": "jtmidres",
        "manufacturer": "JT FPGA",
        "year": 2024
    },
    "assets": [
        {
            "platform": "jtmidres",
            "extensions": [
                "json"
            ],
            "core_specific": true
        },
        {
            "platform": "jtmidres",
            "extensions": [
                "rom"
            ]
        }
    ],
    "requires_license": true,
    "sponsor": {
        "github": [
            "https://github.com/sponsors/jotego"
        ],
        "patreon": "https://www.patreon.com/jotego",
        "custom": [
            "https://www.paypal.me/topapate"
        ]
    },
    "updaters": {
        "license": {
            "filename": "beta.bin"
        }
    }
}
```

### CODE REVIEW

**Comment by joshcampbell191** [comment]
#800

**Comment by mattpannella** [comment]
perfect. this will really come in handy anytime we need to extend what cores can communicate to the updaters without needing any custom additions to the inventory parser

**Review by mattpannella — APPROVED** [review]

**Comment by joshcampbell191** [comment]
Unfortunately, that's not how I implemented the change. I'm still mapping the properties to an object for backwards compatibility in the future.

**Comment by mattpannella** [comment]
ah ok, fair enough. well either way this gets the job done for what we're doing anyway. thanks, josh!

**Review by neil-morrison44 — APPROVED** [review]
Looks good, if possible it’d be good if the serialiser / deserialiser passes through unrecognised things unchanged just to save your efforts if / when anything new gets added to the updaters file.

**Pull request merged**
