### PR TITLE
Tamagotchi core

### PR DESCRIPTION
**Pull request by mattpannella**

### CODE REVIEW

**Comment by mattpannella** [comment]
hm this might be an issue. he has two releases one for pocket and one for mister. if I put the full filename in as the prefix will that work? cuz it's
agg23.Tamagotchi_1.0.0_2023-04-27-Pocket.zip
and
agg23.Tamagotchi_1.0.0_2023-04-27-MiSTer.zip

so there's not really a different prefix haha. the only difference is the full filename

**Comment by mattpannella** [comment]
I put the full filename in and it seems to work but it's got the version in it so that's not gonna work once he updates

**Comment by mattpannella** [comment]
maybe a quick fix would be to add another option for "contains" and instead of check the filename prefix it just looks for the string anywhere in the file name and we could just put "pocket" in for this core

**Comment by joshcampbell191** [comment]
@mattpannella I replaced prefix with filter to allow regex patterns #27. This should give us the flexibility to handle all files.

**Pull request merged**
