### PR TITLE
Initial implementation for replacement cores

### PR DESCRIPTION
**Pull request by joshcampbell191**
Initial implementation for #291.

@neil-morrison44 @mattpannella: Let me know if this suits your initial needs for this functionality. Sorry for the delay.

Note: This will require some additional work to get the `replaced_by` functionality working.

### CODE REVIEW

**Comment by neil-morrison44** [comment]
No worries about the delay, 
The plan for Pocket Sync is to display something in the grid on the core that's installed but has been replaced then do a link to the replacement like:
Screenshot 2023-08-26 at 14 28 25

So for that I'd be looking at the `replaced_by` flag - I get the feeling that `replaces` might be what @mattpannella ends up using though.

---

On the format - the updaters.json should look something like
```json
{
  "previous": [{ "shortname": "2600", "author": "Spiritualized", "platform_id": "2600" }]
}
```
(note that the `previous` array is optional - the `updaters.json` file might get reused in the future to tell the updaters other stuff)

Looks like this sends through the full `previous` array? (which is fine, and probably makes sense)

---

Ideally `replaced_by` would show a single value `${author}.${shortname}` replacement. So:
- `Core A` could be replaced by `Core B` (`Core B` would contain `Core A`'s data in it's `previous` array)
- `Core A`'s `replaced_by` points to `Core B`
- `Core C` replaces _both_ `Core B` and `Core A` (containing both in the `previous` array) 
- the `replaced_by` flag of both `Core A` & `Core B` would point to `Core C`.

Might not happen ever that a core changes name / ownership twice but we may as well cover the situation.

**Comment by joshcampbell191** [comment]
I forgot about re-using the `id` when setting the `replaces` field. I can always make the change if it makes things easier on your end.

**Comment by neil-morrison44** [comment]
As in having it become `replaces: ["agg32.SNES"]`? - I think that’ll be all we need inventory-wise since we’ll be pretty much just using it to find the replacement core’s details (vs reading the other bits from the json when doing installs to find stuff on the filesystem).

Also means malformed `previous` entries won’t get passed through, which is nice too

**Comment by joshcampbell191** [comment]
> As in having it become `replaces: ["agg32.SNES"]`? - I think that’ll be all we need inventory-wise since we’ll be pretty much just using it to find the replacement core’s details (vs reading the other bits from the json when doing installs to find stuff on the filesystem).
> 
> Also means malformed `previous` entries won’t get passed through, which is nice too

I tweaked the code to deserialize the previous object so they can be easily manipulated and am now returning the ID for the replacement.

**Comment by neil-morrison44** [comment]
Is the plan to do `replaced_by` in another PR?

If so - this looks good to me (so I’m happy to approve) but @mattpannella might be more likely to use `replaces` so it’d be good to have his eyes on it too.

I’ve done a PR in Pocket Sync which I think fits this schema (I’m not great at reading Rails though so let me know if I’m miles off): https://github.com/neil-morrison44/pocket-sync/pull/131/files#diff-a9ba9cbedd19c9f66d564d2e89912890209b98f0a7ef19187877d2587300e476R133

**Comment by joshcampbell191** [comment]
@neil-morrison44

> Is the plan to do `replaced_by` in another PR?

Yes. It'll require a little more effort as it requires fetching all `replaces` for each core and then compute the value. 

The only problem I can see with this is that we're not tracking when a core is replaced. This means if multiple cores replace the same one, we'll most likely select the first one.

**Comment by neil-morrison44** [comment]
Yeah, that's an issue - in theory if a core is replaced twice the 2nd replacement will contain both the original core & the 1st replacement in its `previous` array so there may be some way to use that

**Comment by mattpannella** [comment]
took a longer look at this cuz I finally had some free time and I think I'm all good over here. hoping to implement this on my end soon but either way it looks good to me

**Comment by mattpannella** [comment]
don't think you are, but if you were waiting on me to merge this, I'm all set on my end

**Review by neil-morrison44 — APPROVED** [review]

**Comment by joshcampbell191** [comment]
@neil-morrison44 @mattpannella Sorry for the delay on this item. I plan on merging it this weekend assuming everyone's requirements are met.

**Comment by mattpannella** [comment]
no worries, i basically just implemented it by reading the updaters.json locally, but i can easily swap to using the api response once its live

**Comment by neil-morrison44** [comment]
@joshcampbell191 no worries & looks good to me too - Pocket Sync mostly needs to know what a core is replaced _by_ rather than what it replaces - but if the API returns one it’s only a little bit of processing client side to reverse it into the other.

(unless you’re still planning to also implement `replaced_by` for your own usage on the site page or something)

**Comment by joshcampbell191** [comment]
@neil-morrison44 I don't plan on implementing "replaced_by" this release. I should have some time coming up to allow for more development on this project.

**Comment by joshcampbell191** [comment]
Addresses #291

**Pull request merged**
