### PR TITLE
Fix horizontal off-by-one binary image rendering

### PR DESCRIPTION
**Pull request by neil-morrison44**
- My original take on this was off by one as well https://github.com/neil-morrison44/pocket-sync/pull/55/files , no idea why it made sense to subtract one from the width at some point but this should fix it

### CODE REVIEW

**Comment by joshcampbell191** [comment]
Turns out the sizes were correct.

For example, the last column of bytes (x: 521; y: 0-165) of https://github.com/ericlewis/openFPGA-RadarScope/blob/main/dist/Platforms/_images/radarscope.bin are all 0 (which in turn gets translated into a white pixel.

**Comment by neil-morrison44** [comment]
@joshcampbell191 there is an off-by-one error somewhere, https://raw.githubusercontent.com/openfpga-cores-inventory/analogue-pocket/main/assets/images/authors/agg23.SNES.png

This shouldn't have the while line (agg23 noticed it on discord now that Pocket Sync's pulling in the images for uninstalled cores)

**Comment by joshcampbell191** [comment]
@neil-morrison44 The bytes for the last column (x: 35; y: 0 - 35) from the binary image sourced for that icon (https://github.com/agg23/openfpga-SNES/raw/master/dist/Cores/agg23.SNES/icon.bin) also appear to be 0. This seems to indicate the problem is with the source images.

Note that the pixels for the image are stored using a 0 based index (so width -1).

**Comment by neil-morrison44** [comment]
There's something weird going on I think, every image I can find aside from 1 has (what looks like) an erroneous white line on the right:

https://openfpga-cores-inventory.github.io/analogue-pocket/assets/images/platforms/radarscope.png
https://openfpga-cores-inventory.github.io/analogue-pocket/assets/images/platforms/spacerace.png
https://openfpga-cores-inventory.github.io/analogue-pocket/assets/images/authors/pram0d.batrider.png
https://openfpga-cores-inventory.github.io/analogue-pocket/assets/images/authors/boogermann.digdug.png
https://openfpga-cores-inventory.github.io/analogue-pocket/assets/images/platforms/flappybird.png
https://openfpga-cores-inventory.github.io/analogue-pocket/assets/images/platforms/taitosj.png

The only one that actually does anything with the last line is Spacemen3:
https://openfpga-cores-inventory.github.io/analogue-pocket/assets/images/authors/Spacemen3.PDP1.png

Looking at that, I think you're right and it's an error in the _encoding_ rather than the _decoding_ & it bothered me so much in Pocket Sync a while ago that now my decoder there isn't accurate...

Looking at it on the Pocket itself it's hard to tell but I think every image has a larger gap on the left (due to the white line)

**Pull request merged**
